name: SAP Job Automation

on:
  schedule:
    - cron: "0 * * * *"  # Runs hourly at :00
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run Automation Script
        env:
          SAP_USERNAME: ${{ secrets.SAP_USERNAME }}
          SAP_PASSWORD: ${{ secrets.SAP_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          SAP_URL: ${{ secrets.SAP_URL }}
        run: |
          python automation.py || (echo "=== Error Log ===" && cat automation.log && exit 1)

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-logs
          path: |
            automation.log
            error_screenshot.png
