name: SAP Job Automation

on:
  schedule:
    - cron: "0 * * * *"  # Runs at the top of every hour
  workflow_dispatch:

jobs:
  automate-sap:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Verified working version

      - name: Install Chrome
        uses: actions/setup-chrome@v1  # Correct official action
        with:
          chrome-version: latest  # Explicit version specification

      - name: Set up Python
        uses: actions/setup-python@v5  # Latest stable version
        with:
          python-version: '3.10'  # Explicit version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run automation script
        env:
          SAP_USERNAME: ${{ secrets.SAP_USERNAME }}
          SAP_PASSWORD: ${{ secrets.SAP_PASSWORD }}
        run: python automation.py

      - name: Upload error artifacts
        if: failure()
        uses: actions/upload-artifact@v4  # Current version
        with:
          name: error-screenshots
          path: |
            *.png
