# .github/workflows/sap_automation.yml
name: SAP Automation

on:
  schedule:
    - cron: "0 * * * *"  # Hourly execution
  workflow_dispatch:      # Manual trigger

jobs:
  execute-job:
    runs-on: ubuntu-latest # Using Linux runner
    timeout-minutes: 25

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install Chrome and Matching ChromeDriver using a dedicated action
      # This replaces the previous manual installation steps
      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest
        # By default, this installs the latest stable Chrome version
        # and the corresponding compatible ChromeDriver.
        # You could specify a version like this if needed:
        # with:
        #   chrome-version: stable # or 'beta', 'dev', 'canary', or specific version like '114'

      # 4. Install required Python packages
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          # Assumes requirements.txt exists in your repository root
          # and contains at least 'selenium'
          if [ -f requirements.txt ]; then
             pip install -r requirements.txt
          else
             echo "requirements.txt not found, installing selenium directly"
             pip install selenium
          fi

      # 5. Run the automation script
      - name: Run Automation
        env:
          SAP_USERNAME: ${{ secrets.SAP_USERNAME }}
          SAP_PASSWORD: ${{ secrets.SAP_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          SAP_URL: ${{ secrets.SAP_URL }}
        run: |
          echo "--- Verifying Versions ---"
          google-chrome --version
          chromedriver --version
          echo "--------------------------"

          echo "--- Running Python Script ---"
          set -x  # Enable detailed logging for script execution
          python automation.py || { echo 'Automation script failed'; exit 1; }
          set +x
          echo "---------------------------"
