name: SAP Automation Workflow

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  execute-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      DISPLAY: ":99"
      PYTHONUNBUFFERED: 1

    steps:
    - name: Configure X11
      run: |
        sudo apt-get update
        sudo add-apt-repository universe -y
        sudo apt-get install -y \
            xvfb \
            libgbm1 \
            libasound2-plugins \
            libxshmfence1 \
            libnss3 \
            libdrm2
        Xvfb :99 -screen 0 1920x1080x24 &
        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run SAP Automation
      env:
        SAP_USERNAME: ${{ secrets.SAP_USERNAME }}
        SAP_PASSWORD: ${{ secrets.SAP_PASSWORD }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        SAP_URL: ${{ secrets.SAP_URL }}
      run: |
        python automation.py || (echo "=== FAILURE LOG ===" && cat automation.log && exit 1)

    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: automation-artifacts
        path: |
          *.png
          *.log
