name: SAP Job Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"  # Runs daily at 8 AM UTC

jobs:
  run-sap-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google DNS
        run: |
          sudo resolvectl dns eth0 8.8.8.8 8.8.4.4

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install selenium webdriver-manager

      - name: Run SAP Automation Script
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SAP_USERNAME: ${{ secrets.SAP_USERNAME }}
          SAP_PASSWORD: ${{ secrets.SAP_PASSWORD }}
        run: |
          set -x  # Enable debug logs
          source venv/bin/activate
          python automation.py || echo "Script failed. Check logs for details."
