name: SAP Job Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8 AM UTC

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Black formatter
      run: black .

    - name: Run Flake8 linter
      run: flake8 .

    - name: Run SAP Automation
      env:
        SAP_USERNAME: ${{ secrets.SAP_USERNAME }}
        SAP_PASSWORD: ${{ secrets.SAP_PASSWORD }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python automation.py
