name: SAP Job Automation

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  automate-sap:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # ✅ Correct version

      - name: Install Chrome
        uses: actions/setup-chrome@v1  # ✅ Correct action name (NOT browser-actions)
        with:
          chrome-version: latest

      - name: Set up Python
        uses: actions/setup-python@v5  # ✅ Latest version
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run automation
        env:
          SAP_USERNAME: ${{ secrets.SAP_USERNAME }}
          SAP_PASSWORD: ${{ secrets.SAP_PASSWORD }}
        run: python automation.py

      - name: Upload errors
        if: failure()
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: error-screenshots
          path: *.png
