name: SAP Job Automation

on:
  push:
    branches:
      - main

jobs:
  run-sap-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google DNS
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
          echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf > /dev/null

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run SAP Automation Script
        run: |
          python automation.py
