name: SAP Job Automation

on:
  schedule:
    - cron: "0 * * * *"  # Hourly runs
  workflow_dispatch:

jobs:
  automate-sap:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Upgraded to v4

      - name: Set up Chrome
        uses: actions/setup-chrome@v1  # Corrected action name
        with:
          chrome-version: latest

      - name: Set up Python 3.10
        uses: actions/setup-python@v5  # Upgraded to v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run automation
        env:
          SAP_USERNAME: ${{ secrets.SAP_USERNAME }}
          SAP_PASSWORD: ${{ secrets.SAP_PASSWORD }}
        run: |
          python automation.py || (echo "Process failed"; exit 1)
        
      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4  # Upgraded to v4
        with:
          name: error-screenshots
          path: |
            *.png
