name: SAP Job Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          # If your package.json is located in a subdirectory, change directory.
          cd your-folder
          npm install

      - name: Run your command
        run: |
          # Navigate to the correct directory if needed.
          cd your-folder
          npm run your-script
