name: SAP Job Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-automation:
    runs-on: ubuntu-latest
    env:
      # Replace or add additional environment variables if needed.
      SAP_CONFIG: ${{ secrets.SAP_CONFIG }}
      # Example: NODE_ENV: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust node version as needed

      - name: Install Dependencies
        run: npm install

      - name: Run Automation Script
        run: |
          echo "Starting the automation script..."
          # Enable strict error checking and debugging output
          set -euxo pipefail
          # Run the automation command (ensure this command exists in your package.json or is available in your repo)
          npm run automation
        # Optionally, you can add timeout or retry logic here if needed.

      - name: Post-run Cleanup
        if: always()  # This step will run even if the previous step fails
        run: |
          echo "Running post-run cleanup..."
          # Insert any cleanup or diagnostic commands here, for example:
          # cat ./logs/automation.log || echo "No log file found."
