name: SAP Job Automation

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour at the top of the hour
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager python-dotenv

      - name: Run Automation Script
        env:
          SAP_USERNAME: ${{ secrets.SAP_USERNAME }}
          SAP_PASSWORD: ${{ secrets.SAP_PASSWORD }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          set -e
          python automation.py || { echo "Script execution failed"; exit 1; }
